### ISSUE TITLE
Value of type 'NSView' has no member 'backgroundColor'

### ISSUE THREAD

**Issue by thierryH91200** [RichAppz/MacToggle#2]
i have 4 same errors

Value of type 'NSView' has no member 'backgroundColor'

<img width="1115" alt="capture d ecran 2017-01-26 a 07 53 42" src="https://cloud.githubusercontent.com/assets/6251463/22322488/b06ff126-e39c-11e6-818a-b2998c7c1d97.png">

**Comment by RichAppz** [comment]
My mistake, missed out the extension in the upload, this has been rectified. Enjoy.
