### ISSUE TITLE
MacToggle and storyboard

### ISSUE THREAD

**Issue by thierryH91200** [RichAppz/MacToggle#4]
it's me again

I think I miss information/something
How to link MacToggle to storyboard / nib ??

and i have another problem

Detected missing constraints for <graphPG.MacToggle: 0x112ce18f0>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once.

<img width="721" alt="capture d ecran 2017-01-26 a 10 55 46" src="https://cloud.githubusercontent.com/assets/6251463/22327152/102e5364-e3b6-11e6-8c06-7e287bcfd045.png">

and 

import Cocoa

**@IBDesignable**
class MacToggle: NSView {

    //================================================================================
    // MARK: Properties
    //================================================================================

    fileprivate var height: CGFloat
    fileprivate let width: CGFloat

    fileprivate var leftConstraint: NSLayoutConstraint?
    fileprivate var heightConstraint: NSLayoutConstraint?
    fileprivate var widthConstraint: NSLayoutConstraint?

    fileprivate let backVw: NSView = {
        let view = NSView()
        view.wantsLayer = true
        view.layer?.masksToBounds = false
        return view
    }()

    fileprivate let circle: NSView = {
        let view = NSView()

        let shadow = NSShadow()
        shadow.shadowColor = NSColor.black.withAlphaComponent(0.4)
        shadow.shadowOffset = CGSize(width: 0, height: -2)
        shadow.shadowBlurRadius = 2

        view.backgroundColor = .white
        view.wantsLayer = true
        view.shadow = shadow
        view.layer?.borderWidth = 2
        view.layer?.borderColor = NSColor.white.cgColor
        return view
    }()

    fileprivate var _radius: CGFloat?
    fileprivate var backRadius: CGFloat {
        get {
            if let r = _radius { return r }
            return height/2
        }
    }

    fileprivate var circleRadius: CGFloat {
        get {
            if let r = _radius { return r-outlineWidth }
            return (height-(outlineWidth*2))/2
        }
    }

    fileprivate var toggleSize: CGFloat {
        get { return height-(outlineWidth*2) }
    }

    //================================================================================
    // MARK: Callback
    //================================================================================

    var callback: ((_ isOn: Bool) -> Void)?

    //================================================================================
    // MARK: Public Parameters
    //================================================================================

    // MARK: - IBInspectable
    **@IBInspectable** var isOn = false {
        didSet { animate() }
    }

    /// Change the toggle border on and off
    **@IBInspectable** var hasToggleBorder = true {
        didSet { circle.layer?.borderWidth = hasToggleBorder ? toggleBorderWidth : 0 }
    }

    /// Change the width of the outline border
    @IBInspectable var outlineWidth: CGFloat = 2 {
        didSet {
            backVw.layer?.borderWidth = outlineWidth
            layoutSwitch(resetingLayout: true)
        }
    }

    /// Change the width of the border on the toggle
    @IBInspectable var toggleBorderWidth: CGFloat = 2 {
        didSet { circle.layer?.borderWidth = hasToggleBorder ? toggleBorderWidth : 0 }
    }

    /// Change the radius of the complete toggle
    @IBInspectable var radius: CGFloat {
        get {
            if let r = _radius { return r }
            return (height-(outlineWidth*2))/2
        }
        set {
            _radius = newValue
            layoutSwitch()
        }
    }

    /// Change the color of the outline border
    @IBInspectable var outlineColor: NSColor = .lightGray {
        didSet { backVw.layer?.borderColor = outlineColor.cgColor }
    }

    /// Change the color of the fill when the toggle is on
    @IBInspectable var fillColor: NSColor = .lightGray {
        didSet { if isOn { backVw.layer?.borderColor = fillColor.cgColor } }
    }

    /// Change the color of the toggle center
    @IBInspectable var toggleColor: NSColor = .white {
        didSet { circle.backgroundColor = toggleColor }
    }

    /// Change the background color of the complete toggle (visible when switch is off)
    @IBInspectable var backColor: NSColor = .white {
        didSet { backVw.backgroundColor = backColor }
    }

**Comment by RichAppz** [comment]
Let me get back to you on this one, I personally do not use nibs/storyboards.

Thanks

**Comment by RichAppz** [comment]
Ok, seeing as this has been built for auto layout and implementing programmatically the MacToggle will require further development. Feel free to send the branch over with changes you have made so far, if you have fixed it then send a PR; if you are busy then I will look at getting this issue fixed shortly.

**Comment by thierryH91200** [comment]
I'm not sure of myself
Here is attached file
I hesitate to send it to PR
[MacToggle.swift.zip](https://github.com/RichAppz/MacToggle/files/733308/MacToggle.swift.zip)

**Comment by RichAppz** [comment]
Try that I have created a new version

**Comment by thierryH91200** [comment]
it is perfect and thanks

2 examples made in two minutes

<img width="216" alt="capture d ecran 2017-01-26 a 20 30 19" src="https://cloud.githubusercontent.com/assets/6251463/22347000/6d83c832-e406-11e6-9763-a716ea447301.png">

<img width="255" alt="capture d ecran 2017-01-26 a 20 30 08" src="https://cloud.githubusercontent.com/assets/6251463/22346986/678f9762-e406-11e6-9311-e5529f31289b.png">

**Comment by RichAppz** [comment]
Awesome, glad to bring some UIKit over to the Mac - Enjoy and share, don't forget to follow the project for future enhancements. I also have a loader if you require it, but I will have to do the same if you do.

**Comment by thierryH91200** [comment]
I thank you for your speed this will help me a lot for a prettier design
